apiVersion: apps/v1
kind: Deployment
metadata:
  name: flickr-api-deployment
spec:
  selector:
    matchLabels:
      app: flickr-api
  replicas: 2
  template:
    metadata:
      labels:
        app: flickr-api
    spec:
      containers:
      - name: flickr-api
        image: jonbern/flickr-api:latest
        ports:
          - containerPort: 8088
        env:
          - name: PORT
            value: "8088"
          - name: API_KEY
            value: "b09fb8d8f7679bc3c876a5de2cb3f35c"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flickr-frontend-deployment
spec:
  selector:
    matchLabels:
      app: flickr-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: flickr-frontend
    spec:
      containers:
      - name: flickr-frontend
        image: jonbern/flickr-frontend
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
            # IMPORTANT! Run minikube ip and make sure this config matches your minikube IP
            # Also, I'm not sure how this will work outside minikube hosting. Probably need to refernece the external IP of the cluster instead.
          - name: API_BASE_URL
            value: "192.168.99.100:30061/api" 