apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flickr-frontend-deployment
spec:
  selector:
    matchLabels:
      app: flickr-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: flickr-frontend
    spec:
      containers:
      - name: flickr-frontend
        image: jonbern/flickr-frontend
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: PORT
            value: "80"
          - name: API_BASE_URL
            value: "http://ada05fdc93d7d11e8859f02cf1950a80-1294775301.us-east-2.elb.amazonaws.com/api" 