apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flickr-frontend-deployment
spec:
  selector:
    matchLabels:
      app: flickr-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: flickr-frontend
    spec:
      containers:
      - name: flickr-frontend
        image: jonbern/flickr-frontend
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
            # IMPORTANT! Run minikube ip and make sure this config matches your minikube IP
            # Also, I'm not sure how this will work outside minikube hosting. Probably need to refernece the external IP of the cluster instead.
          - name: API_BASE_URL
            value: "http://afcdd7a9d3cc811e8a53c02731388617-71369210.us-east-2.elb.amazonaws.com:8088/api" 