apiVersion: v1
kind: Service
metadata:
  name: flickr-api-service
spec:
  type: "NodePort"
  ports:
  - port: 8088
    nodePort: 30061
    protocol: TCP
  selector:
    app: flickr-api
---
apiVersion: v1
kind: Service
metadata:
  name: flickr-frontend-service
spec:
  type: "LoadBalancer"
  ports:
  - port: 8080
    nodePort: 30062
    protocol: TCP
  selector:
    app: flickr-frontend
